### ISSUE TITLE
systemd unit files

### ISSUE THREAD

**Issue by Mikaela** [Mikaela/shell-things#63]
*In our series, todo lists that have no better places…*

* [x] ZNC ~~user~~ service (for VPS)
    * https://github.com/znc/znc/blob/master/znc.service
    * https://github.com/znc/znc/pull/647 ?
    * http://0pointer.de/public/systemd-man/systemd.exec.html#Environment=
* [x] dnscrypt-proxy service
* [x] Supybot user service
    * https://github.com/Limnoria/Limnoria-doc/issues/69
    * http://0pointer.de/public/systemd-man/systemd.exec.html#Environment=

**Comment by Mikaela** [comment]
Help:
* https://wiki.archlinux.org/index.php/systemd#Writing_unit_files
* https://wiki.archlinux.org/index.php/Systemd/User

**Comment by Fusl** [comment]
Regarding dnscrypt-proxy:
https://github.com/jedisct1/dnscrypt-proxy#running-dnscrypt-proxy-using-systemd

> On a system using systemd, and when compiled with ```--with-systemd```, the proxy can take advantage of systemd's socket activation instead of creating the sockets itself. The proxy will also notify systemd on successful startup.
> 
> Two sockets need to be configured: a UDP socket (```ListenStream```) and a TCP socket (```ListenDatagram```) sharing the same port.
> 
> The source distribution includes the ```dnscrypt-proxy.socket``` and ```dnscrypt-proxy.service``` files that can be used as a starting point.

Since openSUSE (current Linux I use) uses systemd, I will check if I can get it working correctly and update you accordingly.

**Comment by Fusl** [comment]
dnscrypt-proxy systemd setup done:

I needed to install systemd-devel first (```zypper in systemd-devel``` on openSUSE).
Config, compile and install: ```./configure --with-systemd && make && sudo make install```
The systemd files need to be copied manually, for me the path is /usr/lib/systemd/system/: ```cp dnscrypt-proxy.service dnscrypt-proxy.socket /usr/lib/systemd/system/``` and I also needed to symlink the files correctly: ```ln -s /usr/lib/systemd/system/dnscrypt-proxy.service /etc/systemd/system/multi-user.target.wants/dnscrypt-proxy.service; ln -s /usr/lib/systemd/system/dnscrypt-proxy.socket /etc/systemd/system/sockets.target.wants/dnscrypt-proxy.socket```
Also, the ```dnscrypt-proxy.service``` file needs a modification: Change the ```ExecStart=...``` line to ```ExecStart=/usr/local/sbin/dnscrypt-proxy -N <provider-name> -k <provider-key> -r <resolver ip>:<resolver port>```.
Now simply reload systemd: ```systemctl daemon-reload``` and start dnscrypt-proxy: ```systemctl start dnscrypt-proxy```. In case you want to make it boot on startup, you need to enable it: ```systemctl enable dnscrypt-proxy```

**Comment by Mikaela** [comment]
Labeled as waiting as dnscrypt-proxy doesn't support more than one resolver at time and I am not sure if I want to workaround that or if it's better to just wait for support for more resolvers.

**Comment by Mikaela** [comment]
https://github.com/jedisct1/dnscrypt-proxy/issues/72 (https://github.com/jedisct1/dnscrypt-proxy/issues/72#issuecomment-75075710)

**Comment by Mikaela** [comment]
And random note: http://askubuntu.com/q/514063

Minimal custom csv appears to be `Name,Resolver address,Provider name,Provider public key`.

**Comment by Mikaela** [comment]
Not going to happen until dnscrypt-proxy supports multiple servers in one service.
