### ISSUE TITLE
dnscrypt-proxy & captive portals

### ISSUE THREAD

**Issue by Mikaela** [Mikaela/shell-things#95]
Currently I think dnscrypt-proxy breaks captive portal login as the captive portal prevents all connections and it cannot hijack DNS, because it's encrypted.

My ideas so far:

* NetworkManager captive portal checking (with IPFS) on domain that is forwarded to unencrypted resolver by dnscrypt-proxy config.
    * https://cloudflare-ipfs.com/ipfs/QmWFM3kjFXiFp18HSniDG8sd996gfYQnMgduHAh9JbLL7G
    * **mustn't** be https, that is probably getting difficult nowadays. Or has the situation changed and https is fine with captive portal checking for NM?
        * Do I want to send all queries for that domain unencrypted? However they would most likely be done by web browser where IPFS Companion would redirect them to localhost anyway.
* Using Debian/GNOME default URLs?
* Somewhere suggested using `ip -4 route show` and connecting to the default gateway which should get redirected even if the default gateway wasn't running the captive portal.
    * `ip -4 route show|\grep "default"|cut -f3 -d " " `

I think the `ip -4 route show` could be fine at the moment as the only laptop I am responsive for is mine and High SIerra isn't yet EOL forcing me to turn family's vintage MacBook into another Linux laptop.

**Comment by Mikaela** [comment]
Debian: https://packages.debian.org/network-manager-config-connectivity-debian

**Comment by alpsayin** [comment]
Hi Mikaela,

I don't know if this is relevant, but annoyingly a google search to what I thought would be a common problem returns this issue track and only one stackoverflow result. I've scripted out a couple of commands that I issue manually before and after logging into CaptivePortal. Can this be made more programmatic (i.e. no user input at all)?

https://gist.github.com/alpsayin/97321866816bc097fca9b185920c0fed

**Comment by Mikaela** [comment]
Hi, thank you for your comment. I didn't know Google is sending people here, this is just a potential issue I see myself or a family member being hit to in the future and I have been collecting ideas.

I think your script can be helpful, but I don't know how to make it more programmatic as I am not a coder even if my GitHub and especially this repo may seem otherwise to a casual/quick glance.

**Comment by Mikaela** [comment]
https://github.com/jedisct1/dnscrypt-proxy/issues/831#issuecomment-495077021 suggests [Captive Browser](https://github.com/FiloSottile/captive-browser) where I opened an issue about Flat/Snappak (https://github.com/FiloSottile/captive-browser/issues/17) which I could install for family and advice them to use it when they are having problems logging into WLAN, so I think I can close this issue.
